-- View: public.mv_geospatial_combined

-- DROP MATERIALIZED VIEW IF EXISTS public.mv_geospatial_combined;

CREATE MATERIALIZED VIEW IF NOT EXISTS public.mv_geospatial_combined
TABLESPACE pg_default
AS
 SELECT COALESCE(v1.gid, v2.gid, v3.gid, v4.gid, v5.gid, v6.gid, v7.gid, v8.gid, v9.gid, v10.gid, v11.gid) AS gid,
    COALESCE(v1.admin_level, v2.admin_level, v3.admin_level, v4.admin_level, v5.admin_level, v6.admin_level, v7.admin_level, v8.admin_level, v9.admin_level, v10.admin_level, v11.admin_level) AS admin_level,
    COALESCE(v1.date, v2.date, v3.date, v4.date, v5.date, v6.date, v7.date, v8.date, v9.date, v10.date, v11.date) AS date,
    v1."Daily Average Temperature of Air (2m)",
    v1."Daily Total Evaporation",
    v1."Daily Maximun Temperature of Air (2m)",
    v1."Daily Minimun Temperature of Air (2m)",
    v1."Daily Total Surface Net Solar Radiation",
    v1."Daily Total Precipitation",
    v2."Percentage of Employed Men in Lower Nonfarm Jobs",
    v2."Infant Mortality Rate (per 1000 live births)",
    v2."Yearly Average Relative Humidity",
    v2."Yearly Average Surface Temperature (C)",
    v2."Yearly Total Precipitation",
    v2."Population Percentage Age 0-9",
    v2."Population Percentage Age 10-19",
    v2."Population Percentage Age 20-29",
    v2."Population Percentage Age 30-39",
    v2."Population Percentage Age 40-49",
    v2."Population Percentage Age 50-59",
    v2."Population Percentage Age 60-69",
    v2."Population Percentage Age 70-79",
    v2."Population Percentage Age 80-89",
    v2."Population Percentage Age 90+",
    v2."Partners Avg Age Difference ",
    v2."Avg Age at First Marriage (Women 20-50)",
    v2."BMI for Age Z-Score",
    v2."Percentage of Households with a Cellphone",
    v2."Percentage of 1 year olds with DTP3 Vaccine",
    v2."Mean Years Education (Adults 25+)",
    v2."Percentage of Households with Electricity",
    v2."Percentage of Employed Men in Agriculture",
    v2."Height for Age Z-score",
    v2."Average Household Size",
    v2."Percentage of Employed Men in Upper Nonfarm Jobs",
    v2."Percentage of Households with Internet",
    v2."International Wealth Index Score (IWI)",
    v2."Percentage of Poorest Households (IWI Value under 35)",
    v2."Percentage of Poorest Households (IWI Value under 50)",
    v2."Percentage of Poorest Households (IWI Value under 70)",
    v2."Percentage of 1 year olds with Measles Vaccine",
    v2."Average Years of Educations (Men 25+)",
    v2."Percentage of households with Piped Water",
    v2."Percentage of Regional Population Aged 65+",
    v2."Percentage Share of National Population",
    v2."Percentage of Regional Population Aged 15-65",
    v2."Total Area Population",
    v2."Percentage of Stunted Children (0-59 months)",
    v2."Total Fertility Rate",
    v2."Wealth Inequality between Groups",
    v2."Wealth Inequality within Groups",
    v2."Under 5 Mortality Rate",
    v2."Percentage of Urban Population",
    v2."Percentage of Employed Women in Agriculture",
    v2."Weight for Age Z-Score",
    v2."Weight for Height Z-Score",
    v2."Average Years of Education (Women 25+)",
    v2."Percentage of Women in Paid Employment",
    v2."Percentage of Women Employed in Upper Nonfarm Jobs",
    v2."Percentage of Women Employed in Lower Nonfarm Jobs",
    v2."Educational Index",
    v2."Educational Index - Female",
    v2."Educational Index - Male",
    v2."Health Index",
    v2."Health Index - Female",
    v2."Health Index - Male",
    v2."Income Index",
    v2."Log Gross National Income Per Capita ",
    v2."Life Expectancy",
    v2."Life Expectancy (Female)",
    v2."Life Expectancy (Male)",
    v2."GDL - Population Count (pop)",
    v2."Subnational Gender Development Index (SGDI)",
    v2."Subnational Human Development Index (SHDI)",
    v2."Subnational Human Development Index (SHDI) - Female",
    v2."Subnational Human Development Index (SHDI) - Male",
    v3."Monthly Total Burnt Area",
    v4."Root-zone Soil Moisture",
    v5."Conflict Internal Displacements",
    v5."Conflict Total Displacement",
    v5."Disaster Internal Displacements",
    v5."Disaster Total Displacement",
    v5."Conflict Displacements Both Sexes Age 0-4",
    v5."Conflict Displacements Both Sexes Age 5-11",
    v5."Conflict Displacements Both Sexes Age 12-17",
    v5."Conflict Displacements Both Sexes Age 18-59",
    v5."Conflict Displacements Both Sexes Age 60+",
    v5."Conflict Displacements Female Age 0-4",
    v5."Conflict Displacements Female Age 5-11",
    v5."Conflict Displacements Female Age 12-17",
    v5."Conflict Displacements Female Age 18-59",
    v5."Conflict Displacements Female Age 60+",
    v5."Conflict Displacements Male Age 0-4",
    v5."Conflict Displacements Male Age 5-11",
    v5."Conflict Displacements Male Age 12-17",
    v5."Conflict Displacements Male Age 18-59",
    v5."Conflict Displacements Male 60+",
    v5."Disaster Displacements Both Sexes 0-4",
    v5."Disaster Displacements Both Sexes 5-11",
    v5."Disaster Displacements Both Sexes 12-17",
    v5."Disaster Displacements Both Sexes 18-59",
    v5."Disaster Displacements Both Sexes 60+",
    v5."Disaster Displacements Female 0-4",
    v5."Disaster Displacements Female 5-11",
    v5."Disaster Displacements Female 12-17",
    v5."Disaster Displacements Female 18-59",
    v5."Disaster Displacements Female 60+",
    v5."Disaster Displacements Male 0-4",
    v5."Disaster Displacements Male 5-11",
    v5."Disaster Displacements Male 12-17",
    v5."Disaster Displacements Male 18-59",
    v5."Disaster Displacements Male 60+",
    v6."Land Class - Rainfed Cropland Tree or Shrub Cover",
    v6."Land Class - No Data",
    v6."Land Class - Mosaic Tree and Shrub",
    v6."Land Class - Rainfed Cropland",
    v6."Land Class - Mosaic Herbaceous",
    v6."Land Class - Rainfed Cropland Herbaceous Cover",
    v6."Land Class - Shrubland",
    v6."Land Class - Evergreen Shrubland",
    v6."Land Class - Deciduous Shrubland",
    v6."Land Class - Grassland",
    v6."Land Class - Lichens and Mosses",
    v6."Land Class - Sparse Vegetation",
    v6."Land Class - Sparse Tree",
    v6."Land Class - Sparse Shrub",
    v6."Land Class - Sparse Herbaceous",
    v6."Land Class - Flooded Fresh or Brackish Water Tree Cover",
    v6."Land Class - Flooded Saline Water Tree Cover",
    v6."Land Class - Flooded Shrub or Herbaceous Cover",
    v6."Land Class - Urban",
    v6."Land Class - Bare Areas",
    v6."Land Class - Consolidated Bare Areas",
    v6."Land Class - Unconsolidated Bare Areas",
    v6."Land Class - Irrigated Cropland",
    v6."Land Class - Water",
    v6."Land Class - Snow and Ice",
    v6."Land Class - Mosaic Cropland",
    v6."Land Class - Mosaic Natural Vegetation",
    v6."Land Class - Broadleaved Evergreen Tree Closed to Open",
    v6."Land Class - Broadleaved Deciduous Tree Closed to Open",
    v6."Land Class - Broadleaved Deciduous Tree Closed",
    v6."Land Class - Broadleaved Decisuous Tree Open",
    v6."Land Class - Needleleaved Evergreen Tree Closed to Open",
    v6."Land Class - Needleleaved Evergreen Tree Closed",
    v6."Land Class - Needleleaved Evergreen Tree Open",
    v6."Land Class - Needleleaved Deciduous Tree Closed to Open",
    v6."Land Class - Needleleaved Deciduous Tree Closed",
    v6."Land Class - Needleleaved Deciduous Tree Open",
    v6."Land Class - Mixed Tree",
    v7."Daily Average Dust Surface Mass Concentration - PM 2.5",
    v7."Daily Average Organic Carbon Surface Mass Concentration",
    v7."Daily Average Black Carbon Surface Mass Concentration",
    v8."Normalized Difference Vegetation Index",
    v9."WorldPop - Population Count",
    v9."WorldPop - Population Density",
    v10."Total Female Population Age <1",
    v10."Total Female Population Age 1-4",
    v10."Total Female Population Age 5-9",
    v10."Total Female Population Age 10-14",
    v10."Total Female Population Age 15-19",
    v10."Total Female Population Age 20-24",
    v10."Total Female Population Age 25-29",
    v10."Total Female Population Age 30-34",
    v10."Total Female Population Age 35-39",
    v10."Total Female Population Age 40-44",
    v10."Total Female Population Age 45-49",
    v10."Total Female Population Age 50-54",
    v10."Total Female Population Age 55-59",
    v10."Total Female Population Age 60-64",
    v10."Total Female Population Age 65-69",
    v10."Total Female Population Age 70-74",
    v10."Total Female Population Age 75-79",
    v10."Total Female Population Age 80+",
    v10."Total Male Population Age <1",
    v10."Total Male Population Age 1-4",
    v10."Total Male Population Age 5-9",
    v10."Total Male Population Age 10-14",
    v10."Total Male Population Age 15-19",
    v10."Total Male Population Age 20-24",
    v10."Total Male Population Age 25-29",
    v10."Total Male Population Age 30-34",
    v10."Total Male Population Age 35-39",
    v10."Total Male Population Age 40-44",
    v10."Total Male Population Age 45-49",
    v10."Total Male Population Age 50-54",
    v10."Total Male Population Age 55-59",
    v10."Total Male Population Age 60-64",
    v10."Total Male Population Age 65-69",
    v10."Total Male Population Age 70-74",
    v10."Total Male Population Age 75-79",
    v10."Total Male Population Age 80+",
    v10."Total Female Population Aged 0-4 (2021-2022)",
    v10."Total Female Population Aged 5-9 (2021-2022)",
    v10."Total Female Population Aged 10-14 (2021-2022)",
    v10."Total Female Population Aged 15-19 (2021-2022)",
    v10."Total Female Population Aged 20-24 (2021-2022)",
    v10."Total Female Population Aged 25-29 (2021-2022)",
    v10."Total Female Population Aged 30-34 (2021-2022)",
    v10."Total Female Population Aged 35-39 (2021-2022)",
    v10."Total Female Population Aged 40-44 (2021-2022)",
    v10."Total Female Population Aged 45-49 (2021-2022)",
    v10."Total Female Population Aged 50-54 (2021-2022)",
    v10."Total Female Population Aged 55-59 (2021-2022)",
    v10."Total Female Population Aged 60-64 (2021-2022)",
    v10."Total Female Population Aged 65-69 (2021-2022)",
    v10."Total Female Population Aged 70-74 (2021-2022)",
    v10."Total Female Population Aged 75-79 (2021-2022)",
    v10."Total Female Population Aged 80-84 (2021-2022)",
    v10."Total Female Population Aged 85-89 (2021-2022)",
    v10."Total Female Population Aged 90-94 (2021-2022)",
    v10."Total Female Population Aged 95-99 (2021-2022)",
    v10."Total Female Population Aged 100+ (2021-2022)",
    v10."Total Male Population Aged 0-4 (2021-2022)",
    v10."Total Male Population Aged 5-9 (2021-2022)",
    v10."Total Male Population Aged 10-14 (2021-2022)",
    v10."Total Male Population Aged 15-19 (2021-2022)",
    v10."Total Male Population Aged 20-24 (2021-2022)",
    v10."Total Male Population Aged 25-29 (2021-2022)",
    v10."Total Male Population Aged 30-34 (2021-2022)",
    v10."Total Male Population Aged 35-39 (2021-2022)",
    v10."Total Male Population Aged 40-44 (2021-2022)",
    v10."Total Male Population Aged 45-49 (2021-2022) ",
    v10."Total Male Population Aged 50-54 (2021-2022) ",
    v10."Total Male Population Aged 55-59 (2021-2022) ",
    v10."Total Male Population Aged 60-64 (2021-2022) ",
    v10."Total Male Population Aged 65-69 (2021-2022) ",
    v10."Total Male Population Aged 70-74 (2021-2022) ",
    v10."Total Male Population Aged 75-79 (2021-2022) ",
    v10."Total Male Population Aged 80-84 (2021-2022) ",
    v10."Total Male Population Aged 85-89 (2021-2022) ",
    v10."Total Male Population Aged 90-94 (2021-2022) ",
    v10."Total Male Population Aged 95-99 (2021-2022) ",
    v10."Total Male Population Aged 100+ (2021-2022) ",
    v11."WorldPop - Population Weighted Density - Geometric Mean"
   FROM mv_geospatial_era5 v1
     FULL JOIN mv_geospatial_gdl v2 ON COALESCE(v1.gid)::text = v2.gid::text AND COALESCE(v1.admin_level) = v2.admin_level AND COALESCE(v1.date) = v2.date
     FULL JOIN mv_geospatial_gfed v3 ON COALESCE(v1.gid, v2.gid)::text = v3.gid::text AND COALESCE(v1.admin_level, v2.admin_level) = v3.admin_level AND COALESCE(v1.date, v2.date) = v3.date
     FULL JOIN mv_geospatial_gleam v4 ON COALESCE(v1.gid, v2.gid, v3.gid)::text = v4.gid::text AND COALESCE(v1.admin_level, v2.admin_level, v3.admin_level) = v4.admin_level AND COALESCE(v1.date, v2.date, v3.date) = v4.date
     FULL JOIN mv_geospatial_idmc v5 ON COALESCE(v1.gid, v2.gid, v3.gid, v4.gid)::text = v5.gid::text AND COALESCE(v1.admin_level, v2.admin_level, v3.admin_level, v4.admin_level) = v5.admin_level AND COALESCE(v1.date, v2.date, v3.date, v4.date) = v5.date
     FULL JOIN mv_geospatial_landcover v6 ON COALESCE(v1.gid, v2.gid, v3.gid, v4.gid, v5.gid)::text = v6.gid::text AND COALESCE(v1.admin_level, v2.admin_level, v3.admin_level, v4.admin_level, v5.admin_level) = v6.admin_level AND COALESCE(v1.date, v2.date, v3.date, v4.date, v5.date) = v6.date
     FULL JOIN mv_geospatial_merra2 v7 ON COALESCE(v1.gid, v2.gid, v3.gid, v4.gid, v5.gid, v6.gid)::text = v7.gid::text AND COALESCE(v1.admin_level, v2.admin_level, v3.admin_level, v4.admin_level, v5.admin_level, v6.admin_level) = v7.admin_level AND COALESCE(v1.date, v2.date, v3.date, v4.date, v5.date, v6.date) = v7.date
     FULL JOIN mv_geospatial_nvdi v8 ON COALESCE(v1.gid, v2.gid, v3.gid, v4.gid, v5.gid, v6.gid, v7.gid)::text = v8.gid::text AND COALESCE(v1.admin_level, v2.admin_level, v3.admin_level, v4.admin_level, v5.admin_level, v6.admin_level, v7.admin_level) = v8.admin_level AND COALESCE(v1.date, v2.date, v3.date, v4.date, v5.date, v6.date, v7.date) = v8.date
     FULL JOIN mv_geospatial_worldpop v9 ON COALESCE(v1.gid, v2.gid, v3.gid, v4.gid, v5.gid, v6.gid, v7.gid, v8.gid)::text = v9.gid::text AND COALESCE(v1.admin_level, v2.admin_level, v3.admin_level, v4.admin_level, v5.admin_level, v6.admin_level, v7.admin_level, v8.admin_level) = v9.admin_level AND COALESCE(v1.date, v2.date, v3.date, v4.date, v5.date, v6.date, v7.date, v8.date) = v9.date
     FULL JOIN mv_geospatial_worldpop_age_sex v10 ON COALESCE(v1.gid, v2.gid, v3.gid, v4.gid, v5.gid, v6.gid, v7.gid, v8.gid, v9.gid)::text = v10.gid::text AND COALESCE(v1.admin_level, v2.admin_level, v3.admin_level, v4.admin_level, v5.admin_level, v6.admin_level, v7.admin_level, v8.admin_level, v9.admin_level) = v10.admin_level AND COALESCE(v1.date, v2.date, v3.date, v4.date, v5.date, v6.date, v7.date, v8.date, v9.date) = v10.date
     FULL JOIN mv_geospatial_worldpop_pwd v11 ON COALESCE(v1.gid, v2.gid, v3.gid, v4.gid, v5.gid, v6.gid, v7.gid, v8.gid, v9.gid, v10.gid)::text = v11.gid::text AND COALESCE(v1.admin_level, v2.admin_level, v3.admin_level, v4.admin_level, v5.admin_level, v6.admin_level, v7.admin_level, v8.admin_level, v9.admin_level, v10.admin_level) = v11.admin_level AND COALESCE(v1.date, v2.date, v3.date, v4.date, v5.date, v6.date, v7.date, v8.date, v9.date, v10.date) = v11.date
WITH DATA;